language: node_js
node_js:
- '5.0'
- 'stable'
sudo: false
branches:
  except:
  - "/^v[0-9\\.]+/"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: a5ZJCLsRoVln7nMdI6BifpwRFXMN97juzUgbyDUhrxNs0PwfzePuHEP1ybZxrW2Crw5PN+46Ke3eHyfogOAN8TY7m99wyKMFKS01gupTb+0GnYW8JNT2w6g0jSCRJylskS6VkvCmskDJwQ1gFai91+EOacQiAB2PpLk6In4K6T1EevV4SDM5O2BNOLFnV6H+phWkK+P1SeBs7a9x55ynIfSsaHWIlKj8sZAAT1bhPIMZOGrpwnYu2j0d4+FWukZlPboLuBz9xiGDFvAe8Su9+o7qfyEorhx/OlJ5sarCe/SGqfvutzCyJYAQbE4uGjM92IbYFcpNYTARgrHBZUsElW3+mwgq2jsUz+L+C/w1kVYOaGcBDn6459im4xcbPKcnLPAoWCDsTo3AZrdQRU7zJV60+soddnEsPsgiwzKtbUoCqUx8W+gA03oWaoP/emCKK21tCYo8zmcbWTxM4+x1+39hICvG5dkgArpJ1mk2LOKt740SvBkMB3sX2WWdK4V1VSfCsrqC2upZuWK8OqFif8NUEqEP7LwH+LQDUsm7Ik+C6z33ZQNpU7FhUnB83slvTQpFXJaM7u3NqVvq1vClgJktWGQriBG9Xzga0ZSx/TFvvcghQ43IlCA9wmSMEdceGmrmGuDevWGgDosvuLzrbFjDIMAVNKX4jTv0vOZv8bg=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper
- pr-bumper check
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
install:
- npm install
- bower install
script:
- npm run lint
- ember try:one $EMBER_TRY_SCENARIO --- ember test
after_success:
- .travis/publish-coverage.sh
before_deploy:
- pr-bumper bump
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: PmRi76wg33D0eEgbtlAwYiEOTO+6jw3KDP8DMKd04uCJm9lkZdCAIHWcJR9wuyeuz7d8SV/AwJ1EEYV/7RuzPQh9l4yzFE6qTRIqS+PJ57ZB1R4SbBO6KjI4ol9QLpoSF5RpPh3N0LKNo1i5TG7KtfKAEwCuyT3xfFS8s7VmwCkISbCvqt4CqrFh7Y+A9M4roAP/dEeuI/x4kVR4cQAbGaJhuCymDks9zr9ByJfZlK5Ya+HWUnx4QWj3r5yFEE+cF7yIBWYEB3Gla2z40qWKG9Zw7tzxbwFdCym24XAPk3OM5uLxfLLYU4aUHROOzGrXM9rf8JFPsKkrDs1wCoJGGo3yHSZd1hf1MYZjHk4MvKNX8E6w7ekdeEm8wbOL9cobR+RK21CrW7rODVwduYifJ3O00mu6cRqxG/AYvnJtDhE9yTQigACWu64gAR9e2j0mt0/RBNtsibQosvQ0/rbwMfp30pq0wV/hqhc9ax0l1btDif2Iy2DuZkrrcTE8hxCMWKQ8Mb6eiRbIg1z0j2G+GcuyG8U+iOAnajNE8GGyEyZtqa8xBEqYlW1f/2IPXbMYJZSgZIPEFk5ur6DIXMDh3LKb2oitNNyPXNf18Y2yCD80qC36tF5vfp1m4w+fwDDHEeQ2cmxWtpXtCciJK/al8vscdnH/lLJJwIcDcl509hA=
  on:
    branch: master
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: false
after_deploy:
- .travis/publish-gh-pages.sh
notifications:
  slack:
    secure: FQkfsoPmD1UHuBAZyxQ22Z8hWcHf9PjZKcKqL8Dy49cNBkz3rxy/lav0aMg0Ql3C1vL8R0OUGQHrGQG1kBmQhQ2OGBojd/+2PuSorRa0p7ywxctTAudDOzWBM8979eudv8MvcT65U+AtTQR91oSU4JlcejZUtV8dLB4qehEOi8p88ZUmtL5d0cnsU40NdN9rgUndNowAWVnnvYiMatDPcr/FRChDRSngWHnhWOSnjpAKL8sHRATe97hhR3sYk2Nz9z8xBHCiYNvHZgJ5fR9a2Xyp9reeBPPpzEFE/eoAxZMud0sl89FSWhzxnlQfeB+Xdhv2ub9pri+rjqcOMV2yZAkUVBZg/rBjIDlpqY68ppmzc+4ArtA9VNPs1kCQR/NgRq4E0KitKynDk3eCBDH1IPsYHDFT/essqo57rYkdAOAwMEJ/Zo28SYF+UAKh+FzvcbTC+WzSP7e/xogExVqvg3vmaZLSPsOsQ2H4yIstzCjFk1NQdFMkmsLoZHLBf+H2yqQU64bnFvEjAXwTUFz6oYes3hZhJ+Gu5+tyLxe7Y+LXKySKi2L7/NJJ7w0ukp032GVo8cN4s3YK7kmRkG0glXqPmTgGUa1FLAZvz4MAf9fScMkYxTuDz0IS1HMMBL7kHBoda5t1BiIMPy5T21dL+jGRHZZckp0u0URRFqTnIzQ=
